ChemicalSubstancesInventory.MvcApp/Controllers/HomeController.cs
//using ChemicalSubstancesInventory.Model.Enums;
using ChemicalSubstancesInventory.MvcApp.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChemicalSubstancesInventory.MvcApp.Controllers
{
    public partial class HomeController : Controller
    {
        public virtual ActionResult Index()
        {
            return View();
        }

        public virtual ActionResult WorkInProgress()
        {
            return View("WorkInProgress");
        }

        public virtual ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public virtual ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public virtual ActionResult TestBootstrap()
        {
            return View();
        }

        public virtual ActionResult ChangeCulture(CsiCultureEnum lang, string returnUrl)
        {
            if (returnUrl.Length >= 3)
            {
                returnUrl = returnUrl.Substring(3);
            }
            return Redirect("/" + lang.ToString() + returnUrl);
        }
    }
}

ChemicalSubstancesInventory.MvcApp/Controllers/TestController.cs
using ChemicalSubstancesInventory.Model.DataImporters.ImportDataSources;
using ChemicalSubstancesInventory.Model.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ChemicalSubstancesInventory.MvcApp.Controllers
{
    public partial class TestController : Controller
    {
        public virtual ActionResult Index()
        {
            return View();
        }

        public string TestImportAnnexVIExcel()
        {
            string filename = Server.MapPath("~/App_Data/AnnexVIFirst200File.xlsx");
            string returnString = string.Empty;
            var responseBuilder = new StringBuilder();

            using (IChemicalInventoryContext context = new ChemicalInventoryContext())
            {
                //var hazardStatRepo = new GhsHazardStatementAdoRepository(context);
                //var hazardPictRepo = new GhsHazardPictogramAdoRepository(context);
                //var hazardClassRepo = new HazardClassCategoryAdoRepository(context);
                //var substanceRepo = new Substance

                var dataSource = new SubstancesAnnexVIExcelDataSource(filename, context);
                //var dataSource = new SubstancesAnnexVIExcelDataSource(filename, hazardClassRepo, hazardStatRepo, hazardPictRepo, context);

                DateTime startDate = DateTime.Now;

                var result = dataSource.GetSubstances();

                TimeSpan span = DateTime.Now - startDate;
                responseBuilder.AppendLine(span.ToString());

                foreach (var error in dataSource.ErrorList)
                {
                    responseBuilder.AppendLine(string.Format("Annex index no: {0} Error message: {1}", error.IndexNo, error.ErrorMessage));
                }


                foreach (Substance s in result)
                {
                    Substance inDbSubstance = context.Substances.Where(q => q.EcNumber == s.EcNumber).FirstOrDefault();
                    if (inDbSubstance != null)
                    {
                        inDbSubstance.UpdateFromInstance(s);
                    }
                    else
                    {
                        context.Substances.Add(s);
                    }
                    context.SaveChanges();
                }


            }

            if (responseBuilder.Length == 0)
            {
                responseBuilder.AppendLine("OK");
            }

            return responseBuilder.ToString();
        }
    }
}

ChemicalSubstancesInventory.MvcApp/Controllers/TestListController.cs
using ChemicalSubstancesInventory.Model.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChemicalSubstancesInventory.MvcApp.Controllers
{
    public partial class TestListController : Controller
    {
        // GET: TestList
        public virtual ActionResult Index()
        {
            return View();
        }

        public virtual ActionResult HazardStatements()
        {
            List<GhsHazardStatement> list = null;
            using (DbContext context = new ChemicalInventoryContext())
            {
                list = context.Set<GhsHazardStatement>().ToList();
            }

            return View(list);
        }

        public virtual ActionResult HazardClasses()
        {
            List<HazardClass> list = null;
            using (DbContext context = new ChemicalInventoryContext())
            {
                list = context.Set<HazardClass>().ToList();

                foreach (var item in list)
                {
                    item.HazardClassCategories = item.HazardClassCategories.ToList();
                }
            }

            return View(list);
        }

        public virtual ActionResult Substances()
        {
            List<Substance> list = null;

            using (DbContext context = new ChemicalInventoryContext())
            {
                list = context.Set<Substance>().Include(q => q.GhsHazardPictograms).Include(q => q.GhsHazardStatements)
                    .Include(q => q.HazardClassCategories).ToList();
            }

            return View(list);
        }

    }
}

ChemicalSubstancesInventory.MvcApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ChemicalSubstancesInventory.MvcApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ChemicalSubstancesInventory.MvcApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Index</h2>

ChemicalSubstancesInventory.MvcApp/Views/Home/IndexOld.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        <p>Test links</p>
        <p>@Html.ActionLink("Test lists", "Index", "TestList")</p>
        <p>@Html.ActionLink("Test various functionality", "Index", "Test")</p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ChemicalSubstancesInventory.MvcApp/Views/Home/TestBootstrap.cshtml
@{
    ViewBag.Title = "TestBootstrap";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>TestBootstrap</h2>